<?php
/*  Class Generated by Brendon Irwin's Class Generator

	Class: Alias

	type, v
	alias, v
	pointer, v

	
	CREATE TABLE IF NOT EXISTS `alias` (
	`id` INT NULL DEFAULT NULL AUTO_INCREMENT PRIMARY KEY,
	`type` VARCHAR( 55 ),
	`alias` VARCHAR( 55 ),
	`pointer` VARCHAR( 55 )
	);
	
*/

	class Alias{
		private $id;
		private $connection;
		private $errors;
		private $errorCount;
		private $type;
		private $alias;
		private $pointer;


		/*Constructor*/
		function __construct($databaseConnection=null){
			$this->connection = $databaseConnection;
		}

		/*Getters and Setters*/
		function getId(){
			return $this->id;
		}

		function setId($id){
			$this->id = $id;
		}

		function getConnection(){
			return $this->connection;
		}

		function setConnection($connection){
			$this->connection = $connection;
		}

		function getErrors(){
			return $this->errors;
		}

		function setErrors($errors){
			$this->errors = $errors;
		}

		function getErrorCount(){
			return $this->errorCount;
		}

		function setErrorCount($errorCount){
			$this->errorCount = $errorCount;
		}

		function getType(){
			return $this->type;
		}

		function setType($type){
			$this->type = $type;
		}

		function getAlias(){
			return $this->alias;
		}

		function setAlias($alias){
			$this->alias = $alias;
		}

		function getPointer(){
			return $this->pointer;
		}

		function setPointer($pointer){
			$this->pointer = $pointer;
		}

		/*Special Functions*/
		function load($id = null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				if( $id != "" ){
					$query = $this->connection->prepare("SELECT * FROM `alias` WHERE `id` = :id");
					$query->bindParam(':id', $id);
					if( $query->execute() ){
						$alias = $query->fetchObject("alias");
					}
					if( is_object( $alias ) ){
						$alias->setConnection( $this->connection );
					}
					return $alias;
				}
			}
		}

		function getFromPost(){
			$this->setType( (isset($_POST["type"])) ? $_POST["type"] : $this->getType() );
			$this->setAlias( (isset($_POST["alias"])) ? $_POST["alias"] : $this->getAlias() );
			$this->setPointer( (isset($_POST["pointer"])) ? $_POST["pointer"] : $this->getPointer() );
		}

		function getFromRequest(){
			$this->setType( (isset($_REQUEST["type"])) ? $_REQUEST["type"] : $this->getType() );
			$this->setAlias( (isset($_REQUEST["alias"])) ? $_REQUEST["alias"] : $this->getAlias() );
			$this->setPointer( (isset($_REQUEST["pointer"])) ? $_REQUEST["pointer"] : $this->getPointer() );
		}

		function getFromArray($arr){
			$this->setType( (isset($arr["type"])) ? $arr["type"] : $this->getType() );
			$this->setAlias( (isset($arr["alias"])) ? $arr["alias"] : $this->getAlias() );
			$this->setPointer( (isset($arr["pointer"])) ? $arr["pointer"] : $this->getPointer() );
		}

		function compareTo($alias){
			$log = array();
			if($this->getId() != $alias->getId() ){
				$log["Id"] = "modified";
			}else{
				$log["Id"] = "un-modified";
			}
			if($this->getConnection() != $alias->getConnection() ){
				$log["Connection"] = "modified";
			}else{
				$log["Connection"] = "un-modified";
			}
			if($this->getErrors() != $alias->getErrors() ){
				$log["Errors"] = "modified";
			}else{
				$log["Errors"] = "un-modified";
			}
			if($this->getErrorCount() != $alias->getErrorCount() ){
				$log["ErrorCount"] = "modified";
			}else{
				$log["ErrorCount"] = "un-modified";
			}
			if($this->getType() != $alias->getType() ){
				$log["Type"] = "modified";
			}else{
				$log["Type"] = "un-modified";
			}
			if($this->getAlias() != $alias->getAlias() ){
				$log["Alias"] = "modified";
			}else{
				$log["Alias"] = "un-modified";
			}
			if($this->getPointer() != $alias->getPointer() ){
				$log["Pointer"] = "modified";
			}else{
				$log["Pointer"] = "un-modified";
			}
		return $log;
		}

		function save(){
			$id = $this->getId();
			$type = $this->getType();
			$alias = $this->getAlias();
			$pointer = $this->getPointer();
			if( $this->connection ){
				if( $id != "" ){
					/*Perform Update Operation*/
					$query = $this->connection->prepare("UPDATE  `alias` SET `type` = :type ,`alias` = :alias ,`pointer` = :pointer WHERE `id` = :id");
					$query->bindParam('type', $type);
					$query->bindParam('alias', $alias);
					$query->bindParam('pointer', $pointer);
					$query->bindParam('id', $id);
					if( $query->execute() ){
						return $id;
					}else{
						return -1;
					}

				}else{
					/*Perform Insert Operation*/
					$query = $this->connection->prepare("INSERT INTO `alias` (`id`,`type`,`alias`,`pointer`) VALUES (NULL,:type,:alias,:pointer);");
					$query->bindParam(':type', $type);
					$query->bindParam(':alias', $alias);
					$query->bindParam(':pointer', $pointer);

					if( $query->execute() ){
						$this->setId( $this->connection->lastInsertId() );
						return $this->getId();
					}else{
						return -1;
					}	
				}
			}
		}


		function delete($id = null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				if( $id != "" ){
					$query = $this->connection->prepare("DELETE FROM `alias` WHERE `id` = :id");
					$query->bindParam(':id', $id);
					if( $query->execute() ){
						return 1;
					}else{
						return 0;
					}
				}
			}
		}

		function getById($id){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `alias` WHERE `id` = :id LIMIT 1");
				$query->bindParam(':id', $id);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("alias") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByType($type){
			if( $this->connection ){
				if( $type == null && $this->getType() != ""){
					$type = $this->getType();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `alias` WHERE `type` = :type LIMIT 1");
				$query->bindParam(':type', $type);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("alias") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByAlias($alias){
			if( $this->connection ){
				if( $alias == null && $this->getAlias() != ""){
					$alias = $this->getAlias();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `alias` WHERE `alias` = :alias LIMIT 1");
				$query->bindParam(':alias', $alias);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("alias") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByPointer($pointer){
			if( $this->connection ){
				if( $pointer == null && $this->getPointer() != ""){
					$pointer = $this->getPointer();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `alias` WHERE `pointer` = :pointer LIMIT 1");
				$query->bindParam(':pointer', $pointer);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("alias") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}


		function getListById($id=null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `alias` WHERE `id` = :id");
				$query->bindParam(':id', $id);

				if( $query->execute() ){
					while( $result = $query->fetchObject("alias") ){
						$aliass[] = $result;
					}
					if( is_array( $aliass ) ){
						return $aliass;
					}else{
						return array();
					}

				}
			}
		}

		function getListByType($type=null){
			if( $this->connection ){
				if( $type == null && $this->getType() != ""){
					$type = $this->getType();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `alias` WHERE `type` = :type");
				$query->bindParam(':type', $type);

				if( $query->execute() ){
					while( $result = $query->fetchObject("alias") ){
						$aliass[] = $result;
					}
					if( is_array( $aliass ) ){
						return $aliass;
					}else{
						return array();
					}

				}
			}
		}

		function getListByAlias($alias=null){
			if( $this->connection ){
				if( $alias == null && $this->getAlias() != ""){
					$alias = $this->getAlias();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `alias` WHERE `alias` = :alias");
				$query->bindParam(':alias', $alias);

				if( $query->execute() ){
					while( $result = $query->fetchObject("alias") ){
						$aliass[] = $result;
					}
					if( is_array( $aliass ) ){
						return $aliass;
					}else{
						return array();
					}

				}
			}
		}

		function getListByPointer($pointer=null){
			if( $this->connection ){
				if( $pointer == null && $this->getPointer() != ""){
					$pointer = $this->getPointer();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `alias` WHERE `pointer` = :pointer");
				$query->bindParam(':pointer', $pointer);

				if( $query->execute() ){
					while( $result = $query->fetchObject("alias") ){
						$aliass[] = $result;
					}
					if( is_array( $aliass ) ){
						return $aliass;
					}else{
						return array();
					}

				}
			}
		}

		/*Return parameter (object) as Array*/
		function toArray ($obj=null) {
			if (is_object($obj)) $obj = (array)$obj;
			if (is_array($obj)) {
				$new = array();
				foreach ($obj as $key => $val) {
					$class = get_class($this);
					$k = $key;
					$fkey = trim( str_replace( $class,"",$k));
					if( $fkey == "connection" || $fkey == "errors" || $fkey == "errorCount" ){
						//dont add
					}else{
						$new[$fkey] = $this->toArray($val);
					}
				}
			} else {
				$new = $obj;
			}
			return $new;
		}

		/*Return object as Array*/
		function asArray(){
			$array = $this->toArray( $this );
			return $array;
		}

		/*Return object as JSON String*/
		function asJSON(){
			return json_encode($this->asArray());
		}

		/*Return clone of Object*/
		function getClone(){
			return clone($this);
		}


		/*Echo array as CSV file*/
		function arrayToCSVFile($array, $filename="alias.csv", $delimiter=",", $showHeader=true){
			ob_clean();
			if( !is_array($array) ){
				$array = $this->asArray();
			}
			if( !is_array($showHeader) && $showHeader == true){
				$header=array();
				foreach( $array[0] as $key => $value){
					$header[] = strtoupper($key);
				}
				array_unshift($array, $header);
			}
			if( is_array($showHeader) ){
				array_unshift($array, $showHeader);
			}
			header('Content-Type: application/csv; charset=UTF-8');
			header('Content-Disposition: attachement; filename="'.$filename.'";');
			$f = fopen('php://output', 'w');
			foreach ($array as $line) {
				fputcsv($f, $line, $delimiter);
			}
			exit;
		}


		/*getObjectsLikeThis - returns array*/
		function getObjectsLikeThis($asArray=true){
			if( $this->connection ){
				$buildQuery="SELECT * FROM `alias` WHERE ";
				$numParams = 0;
				$values = array();
				foreach ($this as $key => $value) {
					if( $value != "" && $key != "id" && $key != "connection" && $key != "error" && $key != "errorCount"){
						$buildQuery.="`".$key."` = :value_".$numParams." AND ";
						$numParams++;
						$values[] = $value;
					}
				}
				if( $numParams > 0 ){
					//remove last AND
					$buildQuery = substr( $buildQuery , 0, (strlen($buildQuery) -4) );
					
					
					
					$query = $this->connection->PREPARE($buildQuery);
					for($i=0; $i < $numParams; $i++){
						$query->bindParam(":value_".$i, $values[$i]);
					}
					if( $query->execute() ){
						if( $asArray == true ){
							return $query->fetchAll(PDO::FETCH_ASSOC);
						}else{
							$objArray = array();
							while( $result = $query->fetchObject("alias") ){
								$object = $result;
								$objArray[] = $object;
							}
							return $objArray;
						}
					}
				}
			}
		}

		/*get properties*/
		function getObjectsProperties(){
			$properties = array();
			foreach ($this as $key => $value) {
				if( $key != "id" && $key != "connection" && $key != "error" && $key != "errorCount"){
					$properties[] = $key;
				}
			}
			return $properties;
		}
		/*Human readable print out of object*/
		function printFormatted($return=false){
			if($return){
				return '<pre>'.print_r( $this->asArray(), true ).'</pre>';
			}else{
				echo '<pre>'.print_r( $this->asArray(), true ).'</pre>';
			}
		}

	}
?>