<?php
/*  Class Generated by Brendon Irwin's Class Generator

	Class: User

	username, v
	enabled, i
	type, i
	lastlogin, dt

*/

	class User{
		private $id;
		private $connection;
		private $errors;
		private $errorCount;
		private $username;
		private $enabled;
		private $type;
		private $lastlogin;


		/*Constructor*/
		function __construct($databaseConnection=null){
			$this->connection = $databaseConnection;
		}

		/*Getters and Setters*/
		function getId(){
			return $this->id;
		}

		function setId($id){
			$this->id = $id;
		}

		function getConnection(){
			return $this->connection;
		}

		function setConnection($connection){
			$this->connection = $connection;
		}

		function getErrors(){
			return $this->errors;
		}

		function setErrors($errors){
			$this->errors = $errors;
		}

		function getErrorCount(){
			return $this->errorCount;
		}

		function setErrorCount($errorCount){
			$this->errorCount = $errorCount;
		}

		function getUsername(){
			return $this->username;
		}

		function setUsername($username){
			$this->username = $username;
		}

		function getEnabled(){
			return $this->enabled;
		}

		function setEnabled($enabled){
			$this->enabled = $enabled;
		}

		function getType(){
			return $this->type;
		}

		function setType($type){
			$this->type = $type;
		}

		function getLastlogin(){
			return $this->lastlogin;
		}

		function setLastlogin($lastlogin){
			$this->lastlogin = $lastlogin;
		}

		/*Special Functions*/
		function load($id = null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				if( $id != "" ){
					$query = $this->connection->prepare("SELECT * FROM `user` WHERE `id` = :id");
					$query->bindParam(':id', $id);
					if( $query->execute() ){
						$user = $query->fetchObject("user");
					}
					if( is_object( $user ) ){
						$user->setConnection( $this->connection );
					}
					return $user;
				}
			}
		}

		function getFromPost(){
			$this->setUsername( (isset($_POST["username"])) ? $_POST["username"] : $this->getUsername() );
			$this->setEnabled( (isset($_POST["enabled"])) ? $_POST["enabled"] : $this->getEnabled() );
			$this->setType( (isset($_POST["type"])) ? $_POST["type"] : $this->getType() );
			$this->setLastlogin( (isset($_POST["lastlogin"])) ? $_POST["lastlogin"] : $this->getLastlogin() );
		}

		function getFromRequest(){
			$this->setUsername( (isset($_REQUEST["username"])) ? $_REQUEST["username"] : $this->getUsername() );
			$this->setEnabled( (isset($_REQUEST["enabled"])) ? $_REQUEST["enabled"] : $this->getEnabled() );
			$this->setType( (isset($_REQUEST["type"])) ? $_REQUEST["type"] : $this->getType() );
			$this->setLastlogin( (isset($_REQUEST["lastlogin"])) ? $_REQUEST["lastlogin"] : $this->getLastlogin() );
		}

		function getFromArray($arr){
			$this->setUsername( (isset($arr["username"])) ? $arr["username"] : $this->getUsername() );
			$this->setEnabled( (isset($arr["enabled"])) ? $arr["enabled"] : $this->getEnabled() );
			$this->setType( (isset($arr["type"])) ? $arr["type"] : $this->getType() );
			$this->setLastlogin( (isset($arr["lastlogin"])) ? $arr["lastlogin"] : $this->getLastlogin() );
		}

		function compareTo($user){
			$log = array();
			if($this->getId() != $user->getId() ){
				$log["Id"] = "modified";
			}else{
				$log["Id"] = "un-modified";
			}
			if($this->getConnection() != $user->getConnection() ){
				$log["Connection"] = "modified";
			}else{
				$log["Connection"] = "un-modified";
			}
			if($this->getErrors() != $user->getErrors() ){
				$log["Errors"] = "modified";
			}else{
				$log["Errors"] = "un-modified";
			}
			if($this->getErrorCount() != $user->getErrorCount() ){
				$log["ErrorCount"] = "modified";
			}else{
				$log["ErrorCount"] = "un-modified";
			}
			if($this->getUsername() != $user->getUsername() ){
				$log["Username"] = "modified";
			}else{
				$log["Username"] = "un-modified";
			}
			if($this->getEnabled() != $user->getEnabled() ){
				$log["Enabled"] = "modified";
			}else{
				$log["Enabled"] = "un-modified";
			}
			if($this->getType() != $user->getType() ){
				$log["Type"] = "modified";
			}else{
				$log["Type"] = "un-modified";
			}
			if($this->getLastlogin() != $user->getLastlogin() ){
				$log["Lastlogin"] = "modified";
			}else{
				$log["Lastlogin"] = "un-modified";
			}
		return $log;
		}

		function save(){
			$id = $this->getId();
			$username = $this->getUsername();
			$enabled = $this->getEnabled();
			$type = $this->getType();
			$lastlogin = $this->getLastlogin();
			if( $this->connection ){
				if( $id != "" ){
					/*Perform Update Operation*/
					$query = $this->connection->prepare("UPDATE  `user` SET `username` = :username ,`enabled` = :enabled ,`type` = :type ,`lastlogin` = :lastlogin WHERE `id` = :id");
					$query->bindParam('username', $username);
					$query->bindParam('enabled', $enabled);
					$query->bindParam('type', $type);
					$query->bindParam('lastlogin', $lastlogin);
					$query->bindParam('id', $id);
					if( $query->execute() ){
						return $id;
					}else{
						return -1;
					}

				}else{
					/*Perform Insert Operation*/
					$query = $this->connection->prepare("INSERT INTO `user` (`id`,`username`,`enabled`,`type`,`lastlogin`) VALUES (NULL,:username,:enabled,:type,:lastlogin);");
					$query->bindParam(':username', $username);
					$query->bindParam(':enabled', $enabled);
					$query->bindParam(':type', $type);
					$query->bindParam(':lastlogin', $lastlogin);

					if( $query->execute() ){
						$this->setId( $this->connection->lastInsertId() );
						return $this->getId();
					}else{
						return -1;
					}	
				}
			}
		}


		function delete($id = null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				if( $id != "" ){
					$query = $this->connection->prepare("DELETE FROM `user` WHERE `id` = :id");
					$query->bindParam(':id', $id);
					if( $query->execute() ){
						return 1;
					}else{
						return 0;
					}
				}
			}
		}

		function getById($id){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `user` WHERE `id` = :id LIMIT 1");
				$query->bindParam(':id', $id);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("user") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByUsername($username){
			if( $this->connection ){
				if( $username == null && $this->getUsername() != ""){
					$username = $this->getUsername();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `user` WHERE `username` = :username LIMIT 1");
				$query->bindParam(':username', $username);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("user") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByEnabled($enabled){
			if( $this->connection ){
				if( $enabled == null && $this->getEnabled() != ""){
					$enabled = $this->getEnabled();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `user` WHERE `enabled` = :enabled LIMIT 1");
				$query->bindParam(':enabled', $enabled);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("user") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByType($type){
			if( $this->connection ){
				if( $type == null && $this->getType() != ""){
					$type = $this->getType();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `user` WHERE `type` = :type LIMIT 1");
				$query->bindParam(':type', $type);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("user") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByLastlogin($lastlogin){
			if( $this->connection ){
				if( $lastlogin == null && $this->getLastlogin() != ""){
					$lastlogin = $this->getLastlogin();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `user` WHERE `lastlogin` = :lastlogin LIMIT 1");
				$query->bindParam(':lastlogin', $lastlogin);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("user") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}


		function getListById($id=null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `user` WHERE `id` = :id");
				$query->bindParam(':id', $id);

				if( $query->execute() ){
					while( $result = $query->fetchObject("user") ){
						$users[] = $result;
					}
					if( is_array( $users ) ){
						return $users;
					}else{
						return array();
					}

				}
			}
		}

		function getListByUsername($username=null){
			if( $this->connection ){
				if( $username == null && $this->getUsername() != ""){
					$username = $this->getUsername();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `user` WHERE `username` = :username");
				$query->bindParam(':username', $username);

				if( $query->execute() ){
					while( $result = $query->fetchObject("user") ){
						$users[] = $result;
					}
					if( is_array( $users ) ){
						return $users;
					}else{
						return array();
					}

				}
			}
		}

		function getListByEnabled($enabled=null){
			if( $this->connection ){
				if( $enabled == null && $this->getEnabled() != ""){
					$enabled = $this->getEnabled();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `user` WHERE `enabled` = :enabled");
				$query->bindParam(':enabled', $enabled);

				if( $query->execute() ){
					while( $result = $query->fetchObject("user") ){
						$users[] = $result;
					}
					if( is_array( $users ) ){
						return $users;
					}else{
						return array();
					}

				}
			}
		}

		function getListByType($type=null){
			if( $this->connection ){
				if( $type == null && $this->getType() != ""){
					$type = $this->getType();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `user` WHERE `type` = :type");
				$query->bindParam(':type', $type);

				if( $query->execute() ){
					while( $result = $query->fetchObject("user") ){
						$users[] = $result;
					}
					if( is_array( $users ) ){
						return $users;
					}else{
						return array();
					}

				}
			}
		}

		function getListByLastlogin($lastlogin=null){
			if( $this->connection ){
				if( $lastlogin == null && $this->getLastlogin() != ""){
					$lastlogin = $this->getLastlogin();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `user` WHERE `lastlogin` = :lastlogin");
				$query->bindParam(':lastlogin', $lastlogin);

				if( $query->execute() ){
					while( $result = $query->fetchObject("user") ){
						$users[] = $result;
					}
					if( is_array( $users ) ){
						return $users;
					}else{
						return array();
					}

				}
			}
		}

		/*Return parameter (object) as Array*/
		function toArray ($obj=null) {
			if (is_object($obj)) $obj = (array)$obj;
			if (is_array($obj)) {
				$new = array();
				foreach ($obj as $key => $val) {
					$class = get_class($this);
					$k = $key;
					$fkey = trim( str_replace( $class,"",$k));
					if( $fkey == "connection" || $fkey == "errors" || $fkey == "errorCount" ){
						//dont add
					}else{
						$new[$fkey] = $this->toArray($val);
					}
				}
			} else {
				$new = $obj;
			}
			return $new;
		}

		/*Return object as Array*/
		function asArray(){
			$array = $this->toArray( $this );
			return $array;
		}

		/*Return object as JSON String*/
		function asJSON(){
			return json_encode($this->asArray());
		}

		/*Return clone of Object*/
		function getClone(){
			return clone($this);
		}


		/*Echo array as CSV file*/
		function arrayToCSVFile($array, $filename="user.csv", $delimiter=",", $showHeader=true){
			ob_clean();
			if( !is_array($array) ){
				$array = $this->asArray();
			}
			if( !is_array($showHeader) && $showHeader == true){
				$header=array();
				foreach( $array[0] as $key => $value){
					$header[] = strtoupper($key);
				}
				array_unshift($array, $header);
			}
			if( is_array($showHeader) ){
				array_unshift($array, $showHeader);
			}
			header('Content-Type: application/csv; charset=UTF-8');
			header('Content-Disposition: attachement; filename="'.$filename.'";');
			$f = fopen('php://output', 'w');
			foreach ($array as $line) {
				fputcsv($f, $line, $delimiter);
			}
			exit;
		}


		/*getObjectsLikeThis - returns array*/
		function getObjectsLikeThis($asArray=true){
			if( $this->connection ){
				$buildQuery="SELECT * FROM `user` WHERE ";
				$numParams = 0;
				$values = array();
				foreach ($this as $key => $value) {
					if( $value != "" && $key != "id" && $key != "connection" && $key != "error" && $key != "errorCount"){
						$buildQuery.="`".$key."` = :value_".$numParams." AND ";
						$numParams++;
						$values[] = $value;
					}
				}
				if( $numParams > 0 ){
					//remove last AND
					$buildQuery = substr( $buildQuery , 0, (strlen($buildQuery) -4) );
					$query = $this->connection->PREPARE($buildQuery);
					for($i=0; $i < $numParams; $i++){
						$query->bindParam(":value_".$i, $values[$i]);
					}
					if( $query->execute() ){
						if( $asArray == true ){
							return $query->fetchAll(PDO::FETCH_ASSOC);
						}else{
							$objArray = array();
							while( $result = $query->fetchObject("user") ){
								$object = $result;
								$objArray[] = $object;
							}
							return $objArray;
						}
					}
				}
			}
		}

		/*get properties*/
		function getObjectsProperties(){
			$properties = array();
			foreach ($this as $key => $value) {
				if( $key != "id" && $key != "connection" && $key != "error" && $key != "errorCount"){
					$properties[] = $key;
				}
			}
			return $properties;
		}
		/*Human readable print out of object*/
		function printFormatted($return=false){
			if($return){
				return '<pre>'.print_r( $this->asArray(), true ).'</pre>';
			}else{
				echo '<pre>'.print_r( $this->asArray(), true ).'</pre>';
			}
		}

	}
?>